Bloom Engine: bloom::Event::MouseButtonReleased Class Reference
bloom::Event::MouseButtonReleased Class Reference
Represents an event triggered when a mouse button is released.
#include <MouseEvent.hpp>
Public Member Functions
MouseButtonReleased (const int button)
Constructs a MouseButtonReleased.
std::string ToString () const override
Converts the event to a string representation.
Public Member Functions inherited from bloom::Event::MouseButton
int GetMouseButton () const
Retrieves the mouse button involved in the event.
Public Member Functions inherited from bloom::Event::Event
virtual ~Event ()=default
virtual EventType GetEventType () const =0
Gets the type of the event.
virtual const char * GetName () const =0
Gets the name of the event.
virtual int GetCategoryFlags () const =0
Gets the category flags for the event.
std::ostream & operator<< (std::ostream &os) const
Operator << overload.
bool IsInCategory (const EventCategory category) const
Checks if the event belongs to a specific category.
bool IsHandled () const
Indicates whether the event has been handled.
Additional Inherited Members
Protected Member Functions inherited from bloom::Event::MouseButton
MouseButton (int button)
Constructs a MouseButton.
Protected Member Functions inherited from bloom::Event::Event
Event ()=default
Protected Attributes inherited from bloom::Event::MouseButton
int m_button
Protected Attributes inherited from bloom::Event::Event
bool m_handled = false
Detailed Description
Represents an event triggered when a mouse button is released.
Definition at line 133 of file MouseEvent.hpp.
Constructor & Destructor Documentation
MouseButtonReleased()
bloom::Event::MouseButtonReleased::MouseButtonReleased (const int button) inline explicit
Constructs a MouseButtonReleased.
Parameters
button The button that was released.
Definition at line 139 of file MouseEvent.hpp.
References bloom::Event::MouseButton::MouseButton().
Member Function Documentation
ToString()
std::string bloom::Event::MouseButtonReleased::ToString () const inline override virtual
Converts the event to a string representation.
This function returns a string representation of the event, primarily for debugging purposes. Derived classes may override this function to provide more detailed representations.
Returns
A
std::string
containing the string representation of the event.
Reimplemented from bloom::Event::Event.
Definition at line 143 of file MouseEvent.hpp.
References bloom::Event::MouseButton::m_button, and ToString().
Referenced by ToString().
The documentation for this class was generated from the following file:
inc/engine/src/Bloom/Event/MouseEvent.hpp