Bloom Engine: bloom::Engine Class Reference
bloom::Engine Class Reference
Main Bloom engine class.
#include <Engine.hpp>
Public Member Functions
void Run ()
Protected Member Functions
virtual void Begin ()
Called on initialization.
virtual void Tick ()
Called every frame for game logic update.
virtual void Render ()
Called every frame for rendering.
virtual void Close ()
Called when the engine is closing.
Private Member Functions
void Init ()
Private Attributes
std::unique_ptr< Window > m_window
Detailed Description
Main Bloom engine class.
This class contains the core engine code and is responsible for running the game loop. It does not have ownership of the program's entrypoint.
How to use: For any project, you will need to create a class that inherits from Engine and override the Begin, Tick, Render, and Close functions with the desired functionality for the application. It is not needed to add code to every function. From there, you can create an instance of the class on the main function that is owned by the program itself. Then, you just simply call the Run function on the instance. There is no need of use of smart pointers or any other memory management tool as the class will be running for the entire duration of the program.
For simplicity, add the main function in the Application class source file and create the instance of the class there. An example of a main function is defined below:
#include "Sandbox.hpp"
#include <iostream>
int main() {
  auto engine = new game::Application();
  engine->Run();
  return 0;
}
namespace game {
void Application::Begin() {
  // Example of overriding functionality
  Engine::Begin();
  std::cout << "[SANDBOX] Hello World!\n";
}
}
Definition at line 52 of file Engine.hpp.
Member Function Documentation
Begin()
virtual void bloom::Engine::Begin () inline protected virtual
Called on initialization.
Reimplemented in game::Application.
Definition at line 67 of file Engine.hpp.
Referenced by Init().
Close()
void bloom::Engine::Close () protected virtual
Called when the engine is closing.
Definition at line 27 of file Engine.cpp.
Referenced by Run().
Init()
void bloom::Engine::Init () private
This function is used for initializing the engine. It is called before the game loop starts.
It is a private function that should not be called directly. It is called by the Run function. Adding functionality on the init is done on the begin function. It is separated like this because you will want to add functionality in between parts of the Init function, not directly at the end. For that, the Begin funciton is provided. It will be called during the engine initialization.
Definition at line 17 of file Engine.cpp.
References Begin(), bloom::Log::Init(), and m_window.
Referenced by Run().
Render()
void bloom::Engine::Render () protected virtual
Called every frame for rendering.
Definition at line 25 of file Engine.cpp.
Referenced by Run().
Run()
void bloom::Engine::Run ()
Note
Call this to start the engine on the main function
Definition at line 6 of file Engine.cpp.
References Close(), Init(), m_window, Render(), and Tick().
Tick()
void bloom::Engine::Tick () protected virtual
Called every frame for game logic update.
Definition at line 24 of file Engine.cpp.
Referenced by Run().
Member Data Documentation
m_window
std::unique_ptr<Window> bloom::Engine::m_window private
Definition at line 73 of file Engine.hpp.
Referenced by Init(), and Run().
The documentation for this class was generated from the following files:
inc/engine/src/Bloom/Engine.hpp
inc/engine/src/Bloom/Engine.cpp