Bloom Engine: bloom::Event::Event Class Reference
bloom::Event::Event Class Reference abstract
Abstract base class for all events in the Bloom Engine.
#include <Event.hpp>
Public Member Functions
virtual ~Event ()=default
virtual EventType GetEventType () const =0
Gets the type of the event.
virtual const char * GetName () const =0
Gets the name of the event.
virtual int GetCategoryFlags () const =0
Gets the category flags for the event.
virtual std::string ToString () const
Converts the event to a string representation.
std::ostream & operator<< (std::ostream &os) const
Operator << overload.
bool IsInCategory (const EventCategory category) const
Checks if the event belongs to a specific category.
bool IsHandled () const
Indicates whether the event has been handled.
Protected Member Functions
Event ()=default
Protected Attributes
bool m_handled = false
Friends
class Dispatcher
Detailed Description
Abstract base class for all events in the Bloom Engine.
The Event class serves as the base for all event types. It provides a common interface for retrieving the event type, name, and category flags. Events can also be converted to string representations and checked against specific categories. Derived event classes must override the pure virtual functions to provide specific details for each event type.
Definition at line 86 of file Event.hpp.
Constructor & Destructor Documentation
Event()
bloom::Event::Event::Event () protected default
~Event()
virtual bloom::Event::Event::~Event () virtual default
Member Function Documentation
GetCategoryFlags()
virtual int bloom::Event::Event::GetCategoryFlags () const nodiscard pure virtual
Gets the category flags for the event.
This is a pure virtual function that must be implemented by all derived event classes. It returns the category flags for the event, which can be used to filter events by category.
Returns
An integer representing the category flags of the event.
Referenced by IsInCategory().
GetEventType()
virtual EventType bloom::Event::Event::GetEventType () const nodiscard pure virtual
Gets the type of the event.
This is a pure virtual function that must be implemented by all derived event classes. It returns the type of the event, allowing it to be identified at runtime.
Returns
The EventType of the event.
GetName()
virtual const char * bloom::Event::Event::GetName () const nodiscard pure virtual
Gets the name of the event.
This is a pure virtual function that must be implemented by all derived event classes. It returns the name of the event as a string.
Returns
A
const char*
representing the name of the event.
Referenced by ToString().
IsHandled()
bool bloom::Event::Event::IsHandled () const inline nodiscard
Indicates whether the event has been handled.
This function returns a boolean value indicating whether the event has been handled. If the event has been handled, it should not be processed further.
Returns
true if the event has been handled; otherwise, false.
Definition at line 157 of file Event.hpp.
References m_handled.
IsInCategory()
bool bloom::Event::Event::IsInCategory (const EventCategory category) const inline nodiscard
Checks if the event belongs to a specific category.
This function performs a bitwise comparison to determine if the event's category flags include the specified category.
Parameters
category The EventCategory to check against.
Returns
true if the event belongs to the specified category; otherwise, false.
Definition at line 147 of file Event.hpp.
References GetCategoryFlags().
operator<<()
std::ostream & bloom::Event::Event::operator<< (std::ostream & os) const inline
Operator << overload.
Definition at line 136 of file Event.hpp.
References ToString().
ToString()
virtual std::string bloom::Event::Event::ToString () const inline nodiscard virtual
Converts the event to a string representation.
This function returns a string representation of the event, primarily for debugging purposes. Derived classes may override this function to provide more detailed representations.
Returns
A
std::string
containing the string representation of the event.
Reimplemented in bloom::Event::KeyPressed, bloom::Event::KeyReleased, bloom::Event::KeyTyped, bloom::Event::MouseButtonPressed, bloom::Event::MouseButtonReleased, bloom::Event::MouseMoved, bloom::Event::MouseScrolled, and bloom::Event::WindowResize.
Definition at line 133 of file Event.hpp.
References GetName().
Referenced by operator<<().
Friends And Related Symbol Documentation
Dispatcher
friend class Dispatcher friend
Definition at line 87 of file Event.hpp.
References Dispatcher.
Referenced by Dispatcher.
Member Data Documentation
m_handled
bool bloom::Event::Event::m_handled = false protected
Indicates whether the event has been handled.
Definition at line 160 of file Event.hpp.
Referenced by IsHandled().
The documentation for this class was generated from the following file:
inc/engine/src/Bloom/Event/Event.hpp