Bloom Engine: bloom::MouseButtonPressedEvent Class Reference
bloom::MouseButtonPressedEvent Class Reference
Represents an event triggered when a mouse button is pressed.
#include <MouseEvent.hpp>
Public Member Functions
MouseButtonPressedEvent (const int button)
Constructs a MouseButtonPressedEvent.
std::string ToString () const override
Public Member Functions inherited from bloom::MouseButtonEvent
int GetMouseButton () const
Retrieves the mouse button involved in the event.
Additional Inherited Members
Protected Member Functions inherited from bloom::MouseButtonEvent
MouseButtonEvent (int button)
Constructs a MouseButtonEvent.
Protected Attributes inherited from bloom::MouseButtonEvent
int m_button
Detailed Description
Represents an event triggered when a mouse button is pressed.
Definition at line 112 of file MouseEvent.hpp.
Constructor & Destructor Documentation
MouseButtonPressedEvent()
bloom::MouseButtonPressedEvent::MouseButtonPressedEvent (const int button) inline explicit
Constructs a MouseButtonPressedEvent.
Parameters
button The button that was pressed.
Definition at line 118 of file MouseEvent.hpp.
References bloom::MouseButtonEvent::MouseButtonEvent().
Member Function Documentation
ToString()
std::string bloom::MouseButtonPressedEvent::ToString () const inline override
Definition at line 122 of file MouseEvent.hpp.
References bloom::MouseButtonEvent::m_button, and ToString().
Referenced by ToString().
The documentation for this class was generated from the following file:
src/Bloom/Event/MouseEvent.hpp