Bloom Engine: bloom::Key Class Reference
bloom::Key Class Reference
Base class for all keyboard events.
#include <KeyEvent.hpp>
Public Member Functions
int GetKeyCode () const
Retrieves the key code associated with the event.
Protected Member Functions
Key (const int keycode)
Protected Attributes
int m_keyCode
Detailed Description
Base class for all keyboard events.
The Key class provides the common functionality for keyboard-related events, such as retrieving the key code of the event. This class is designed to be extended by specific event types, such as KeyPressed and KeyReleasedEvent.
Definition at line 26 of file KeyEvent.hpp.
Constructor & Destructor Documentation
Key()
bloom::Key::Key (const int keycode) inline explicit protected
Definition at line 37 of file KeyEvent.hpp.
References m_keyCode.
Referenced by bloom::KeyPressed::KeyPressed(), bloom::KeyReleased::KeyReleased(), and bloom::KeyTyped::KeyTyped().
Member Function Documentation
GetKeyCode()
int bloom::Key::GetKeyCode () const inline nodiscard
Retrieves the key code associated with the event.
Returns
The key code as an integer.
Definition at line 32 of file KeyEvent.hpp.
References m_keyCode.
Member Data Documentation
m_keyCode
int bloom::Key::m_keyCode protected
Definition at line 39 of file KeyEvent.hpp.
Referenced by GetKeyCode(), Key(), bloom::KeyPressed::ToString(), bloom::KeyReleased::ToString(), and bloom::KeyTyped::ToString().
The documentation for this class was generated from the following file:
src/Bloom/Event/KeyEvent.hpp