Bloom Engine: bloom::KeyEvent Class Reference
bloom::KeyEvent Class Reference
Base class for all keyboard events.
#include <KeyEvent.hpp>
Public Member Functions
int GetKeyCode () const
Retrieves the key code associated with the event.
Public Member Functions inherited from bloom::Event
virtual ~Event ()=default
virtual EventType GetEventType () const =0
Gets the type of the event.
virtual const char * GetName () const =0
Gets the name of the event.
virtual int GetCategoryFlags () const =0
Gets the category flags for the event.
virtual std::string ToString () const
Converts the event to a string representation.
std::ostream & operator<< (std::ostream &os) const
Operator << overload.
bool IsInCategory (const EventCategory category) const
Checks if the event belongs to a specific category.
bool IsHandled () const
Indicates whether the event has been handled.
Protected Member Functions
KeyEvent (const int keycode)
Protected Member Functions inherited from bloom::Event
Event ()=default
Protected Attributes
int m_keyCode
Protected Attributes inherited from bloom::Event
bool m_handled = false
Detailed Description
Base class for all keyboard events.
The KeyEvent class provides the common functionality for keyboard-related events, such as retrieving the key code of the event. This class is designed to be extended by specific event types, such as KeyPressedEvent and KeyReleasedEvent.
Definition at line 26 of file KeyEvent.hpp.
Constructor & Destructor Documentation
KeyEvent()
bloom::KeyEvent::KeyEvent (const int keycode) inline explicit protected
Definition at line 37 of file KeyEvent.hpp.
References m_keyCode.
Referenced by bloom::KeyPressedEvent::KeyPressedEvent(), bloom::KeyReleasedEvent::KeyReleasedEvent(), and bloom::KeyTypedEvent::KeyTypedEvent().
Member Function Documentation
GetKeyCode()
int bloom::KeyEvent::GetKeyCode () const inline nodiscard
Retrieves the key code associated with the event.
Returns
The key code as an integer.
Definition at line 32 of file KeyEvent.hpp.
References m_keyCode.
Member Data Documentation
m_keyCode
int bloom::KeyEvent::m_keyCode protected
Definition at line 39 of file KeyEvent.hpp.
Referenced by GetKeyCode(), KeyEvent(), bloom::KeyPressedEvent::ToString(), bloom::KeyReleasedEvent::ToString(), and bloom::KeyTypedEvent::ToString().
The documentation for this class was generated from the following file:
src/Bloom/Event/KeyEvent.hpp